#!/bin/bash
SCAN_RESULT=/tmp/connman.scan
STORAGE_PATH=/var/lib/connman

get_services() {
    : > $SCAN_RESULT
    trap "rm -f $SCAN_RESULT" EXIT
    connmanctl enable wifi &>/dev/null
    connmanctl scan wifi &>/dev/null
    sleep 1
    local IFS=$'\n'
    local line
    for line in $(connmanctl services | tr -s ' '); do
        # point to the end
        local count="$(sed 's/[^ ]//g' <<<"$line" | wc -c)"
        # 1. state 2. name 3. id
        if (( $count >= 3 )); then
            local name="$(cut -d ' ' -f "2-$(( count - 1 ))" --output-delimiter _ <<<"$line")"
            local service_id="$(cut -d ' ' -f $count <<<"$line")"
            if [[ "$service_id" =~ ^wifi_ ]]; then
                echo "$name $service_id" >> $SCAN_RESULT
            fi
        fi
    done
}

count_services() {
    [[ -f $SCAN_RESULT ]] && wc -l < $SCAN_RESULT || echo 0
}

# $1 = index
index_to_name() {
    [[ -f $SCAN_RESULT ]] || exit 1
    sed -n "$1p" $SCAN_RESULT | cut -d ' ' -f 1
}

# $1 = index
index_to_service() {
    [[ -f $SCAN_RESULT ]] || exit 1
    sed -n "$1p" $SCAN_RESULT | cut -d ' ' -f 2
}

# $1 = service id
get_service_security() {
    cut -d _ -f 5 <<<"$1"
}

# $1 = service id
get_service_signal() {
    connmanctl services "$1" | grep Strength | tr -s ' ' | cut -d ' ' -f 4
}

# $1 = service id
get_service_state() {
    connmanctl services "$1" | grep State | tr -s ' ' | cut -d ' ' -f 4
}

create_dmenu() {
    [[ -f $SCAN_RESULT ]] || exit 1
    local IFS=$'\n'
    local order=1
    local line
    for line in $(< $SCAN_RESULT); do
        local service_id="$(cut -d ' ' -f 2 <<<"$line")"
        local name="$(cut -d ' ' -f 1 <<<"$line")"
        local security="$(get_service_security "$service_id")"
        local signal="$(get_service_signal "$service_id")"
        local disconnect=""
        [[ "online" == "$(get_service_state "$service_id")" ]] && disconnect="(disconnect)"

        echo "$order | $name | security: $security | signal: $signal $disconnect"
        (( order++ ))
    done
}

# $1 = msg
dmenu_notify() {
    : | dmenu -p "$1 (press enter)"
}

if [[ $EUID != 0 ]]; then 
    dmenu_notify "Please run it as root"
    exit 1
fi

get_services
index="$(create_dmenu | dmenu -l "$(count_services)" -i -p "Select one wifi service" | cut -d ' ' -f 1)"
[[ "$index" =~ ^[0-9]+$ ]] || exit 1

name="$(index_to_name "$index")"
service_id="$(index_to_service "$index")"
echo "$name { $service_id }"

if [[ "online" == "$(get_service_state "$service_id")" ]]; then
    connmanctl disconnect "$service_id"
    dmenu_notify "$name disconnected"
    exit 0
fi

security="$(get_service_security "$service_id")"
if [[ "$security" == none ]]; then
    # do nothing
    echo "no security"
elif [[ "$security" == ieee8021x || "$security" == psk || "$security" == wep ]]; then
    config_file="${STORAGE_PATH}/${name}-${security}.config"
    identity=""
    password=""
    if [[ -f $config_file && "no" != "$(echo -e "yes\nno" | dmenu -p "Use previous profile?")" ]]; then
        echo "use old profile: $config_file"
    else
        # create service file
        [[ "$security" == ieee8021x ]] && identity="$(: | dmenu -p "Please provide identity")"
        password="$(: | dmenu -p "Please provide password")"

        if [[ "$password" == "" ]]; then
            dmenu_notify "Invalid identity or password"
            exit 1
        fi
        if [[ "$security" == ieee8021x ]]; then
            cat > $config_file <<EOF
[service_$service_id]
Type = wifi
Name = $name
EAP = peap
Phase2 = MSCHAPV2
Identity = $identity
Passphrase = $password
EOF
        elif [[ "$security" == psk || "$security" == wep ]]; then 
            cat > $config_file <<EOF
[service_$service_id]
Type = wifi
Name = $name
Passphrase = $password
EOF
        fi
    fi

fi

connman_msg="$(connmanctl connect "$service_id" 2>&1 | head -n 1)"
if grep -qi ^connected <<<"$connman_msg" ; then
    dmenu_notify "connected to $name"
else
    error_msg="$(cut -d ' ' -f 3- <<<"$connman_msg")"
    dmenu_notify "cannot connect to $name ($error_msg)"
fi
